version: '3.8'

services:
  web:
    build:
      context: apps/web
    container_name: web
    hostname: web
    restart: always
    depends_on:
      - postgres
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    hostname: localhost
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    #      - kbase
    networks:
      - app-net

  postgres:
    image: postgres:16
    container_name: novodata
    hostname: novodata
    restart: always
    ports: # indev prisma migrations?
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: catsrule
      POSTGRES_DB: novo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
