include:
  - common.yaml

services:
  web:
    build:
      context: ../../apps/web
    container_name: web
    restart: always
    depends_on:
      - postgres
    networks:
      - app-net

#  kbase:
#    build:
#      context: ./apps/kbase
#    container_name: kbase
#    networks:
#      - app-net